### ISSUE TITLE
Unable to set temperature on colourtuneablelight

### ISSUE THREAD

**Issue by dantchapman** [Rendili/pyhiveapi#1]
I tried the latest version (I use jupiter so I can interactively play with the lights)

```
from pyhiveapi import pyhiveapi
papi  = pyhiveapi.Pyhiveapi()
papi.initialise_api("xxxx", "xxxx", 2)
papi.Light.get_color_temp(papi,node_id='xxxxxxx')
```
->370

`papi.Light.set_colour_temp(papi, node_id='xxxxxxx', new_colour_temp=200)`
->True
`papi.Light.get_color_temp(papi,node_id='xxxxxxx')
`
->370

if I set the colour to a different setting in hive:
`papi.Light.get_color_temp(papi,node_id='xxxxxxx')
`
->169

I confirm that I can set brightness and switch the lamp on and off. Also I note that we have a mix of colour and color :)

**Comment by dantchapman** [comment]
The fix is to include the switch for the colour status:
```
                        json_string_content = ('{"colourMode": "WHITE", "colourTemperature": '
                                                + str(new_colour_temp)
                                                + '}')
```

Checkout https://github.com/alyc100/SmartThingsPublic/blob/master/devicetypes/alyc100/hive-active-light-colour-tuneable.src/hive-active-light-colour-tuneable.groovy 

I don't know enough about hass for the integration, but should give a good start for fully implementing colourtunable bulb

**Comment by KJonline** [comment]
@Dantchapman

Are you trying to set the colour temperature on a colour bulb? Sorry I miss understood I thought it wasn’t working on a tunable bulb without colour.

Yes it won’t work on colour bulbs just yet as the official hive release doesn’t support them. I am converting all the colour code which I previously did and moving it into the library ready for the next release.

**Comment by dantchapman** [comment]
Ah - I thought that it was just that the colour was not supported. I tried to make that clear in the issue message. Right now I have what I need to set the scenes as I want. I’m also happy to contribute further once you are ready.

**Comment by dantchapman** [comment]
I have implemented the colour methods in my environment:

1. added method to get and set hue and saturation (no complex math required - almost identical to brightness (actually I use a single method for hue and sat together)
2. Used colorsys.hsv_to_rgb(hue,sat,val) and  colorsys.rgb_to_hsv(red,green,blue) to convert between the HA colour wheel and the light. Simply adding ATTR_RGB_COLOR and SUPPORT_RGB_COLOR as well as the supporting methods in the hive.py light code.
3. The assumption is the v is always 1 (100).

If helpful I can send the code.

**Comment by KJonline** [comment]
Hi @dantchapman

The colour support code has been completed and accepted by the Home Assistant devs. They have merged it with there branch we are just waiting for the next release and it will be included which will be 0.61.  

Looking at your point about the Home assistant api for converting colour types. It didn’t seem to be accurate when I was trialling it so I did my own conversion.

Point 3 I’m not sure if the value is always 100. My investigation  pointed me in the direction advising it was the brightness off the colour. But I don’t have a colour bulb so can confirm.

**Comment by dantchapman** [comment]
Yes value and brightness seem to be equivalent in the hive bulb....
However the HA wheel seems to only generate RGB codes where value = 1. Also I did NOT want to change the brightness of the bulb when changing the colour.
The built in api seems to work pretty well - conversion to from HSV-RGB seems pretty consistent. I also started by writing my own - but have reverted to the build in colorsys module. You sometimes notice a small hop in the wheel when changing the colour - but it is very slight.

**Comment by dantchapman** [comment]
I've done some further investigation - trying some colours that don't have a 'Value' of 1 don't seem to work. At least they don't work if using the attribute Light_value. Either the hive bulb does not really understand HSV fully or the python colorsys api is wrong. I'm tempted to assume that it is the hive bulb at fault. Therefore I will stand by continuing to assume that V=1.

By the way - what is interesting is that setting the 'Light_value' allows to change colour and brightness in one call - this is pretty useful. I've added a separate method to send hue, saturation and value in a single call.

**Comment by Rendili** [comment]
Home Assistant 0.61.0 has now been released which uses the latest colour  bulb code
@dantchapman does this now enable you to set colours in the colour bulb as expected?
