### ISSUE TITLE
turn_boost_on issue

### ISSUE THREAD

**Issue by wtluke** [Rendili/pyhiveapi#2]
I'm getting the following error when trying to use `turn_boost_on`:

`AttributeError: 'Pyhiveapi' object has no attribute 'min_temperature'`

I've checked I'm using the correct node (I only have Hive Heating). A bug in expecting min_temperature to exist?

```
import pyhiveapi
papi  = pyhiveapi.Pyhiveapi()
papi.initialise_api("x", "x", 2)
node = 'z'
papi.Heating.turn_boost_on(papi,node,15,19)
#print(papi.Heating.get_state(papi,node))
```

Thanks for a brilliant api.

**Comment by Rendili** [comment]
Glad you like the library

I have added an example file to GitHub, please could you try this and see if it is working for you?

It contains a few different types of examples on how to interact with the library and will do the following:
- Initialise the api and log in with credentials
- Cycle through each found device
- Get NodeID's for heating and hotwater
- Perform some gets and sets for heating

[pyhiveapi_example_1.py](https://github.com/Rendili/pyhiveapi/blob/master/examples/pyhiveapi_example_1.py)

Thanks
