### ISSUE TITLE
New issue with binary_sensors not updating

### ISSUE THREAD

**Issue by tmoore22** [Rendili/pyhiveapi#3]
repeated errors:

`Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 212, in async_update_ha_state
    state = self.state
  File "/usr/lib/python3.6/site-packages/homeassistant/components/binary_sensor/__init__.py", line 72, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/usr/lib/python3.6/site-packages/homeassistant/components/binary_sensor/hive.py", line 59, in is_on
    self.node_device_type)
  File "/config/deps/lib/python3.6/site-packages/pyhiveapi/pyhiveapi.py", line 2162, in get_state
    sensor_state_tmp = (HSC.products.sensors[node_index]["props"]["motion"]["status"])
KeyError: 'status'`

**Comment by KJonline** [comment]
@tmoore22

What version if motion sensor do you have? V1 the square one or V2 the thin rectangle device?

We have had an issue recently with the motion sensor always returning False but not that it couldn’t find the “status” tag in the JSON.

**Comment by KJonline** [comment]
@tmoore22

Are you using the library with Home Assistant or on its own?

**Comment by tmoore22** [comment]
They are all the new v2 sensors, I have also update the pyhive from git within my hassio install (docker) using latest.

I do have some sensors that are assigned to hive but are currently offline(flat battery) that's likely the issue.. But not handled very well..

Thanks! Tim

**Comment by tmoore22** [comment]
With home assistant

**Comment by KJonline** [comment]
@tmoore22

That shouldn’t be an issue hive store all the device data on there server and the api we hit gets the information from the server not the device. So it should be receiving the last known state from the server. As hive poll there devices they should update a field on there server for that node to set it too offline but the state information should still be available.

It will be interesting to see if you still get the same errors after the next Home Assistant release as the new version has check made before getting status to see if the device is offline or not

**Comment by KJonline** [comment]
@tmoore22

Sorry that last paragraph was supposed to say when the next home assistant release with hive in it (we don’t know when that will be yet) is released there will be checks when getting the states of devices to see if it is online or offline

**Comment by tmoore22** [comment]
Will take and download as soon as available.. Will update here when result is known..
________________________________

**Comment by tmoore22** [comment]
I have already downloaded the latest pyhive (0.22?) from github and update my home assistant install with the new released pyhive... Problem still exists!
________________________________

**Comment by KJonline** [comment]
Hi @tmoore22

Yes the changes I was referring to have not been published yet they are still in development but when we do publish them as a pyhiveapi update. It will be interesting to see if you get the errors I’ll comment here when we have published it.

**Comment by KJonline** [comment]
Hi @tmoore22

Has this issue been resolved with the release of Home assistant 0.68?

Please could you confirm.

**Comment by tmoore22** [comment]
Hi,

hive.py now fails to start (after 3 retries) ☹

2018-04-29 23:10:20 ERROR (MainThread) [homeassistant.setup] Error during setup of component hive Traceback (most recent call last): File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 145, in _async_setup_component component.setup, hass, processed_config) File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run result = self.fn(*self.args, **self.kwargs) File "/usr/lib/python3.6/site-packages/homeassistant/components/hive.py", line 76, in setup session.attributes = Pyhiveapi.Attributes()

Rgds,
Timothy

**Comment by KJonline** [comment]
@tmoore22

Looking at the error your home assistant hasn’t upgraded pyhiveapi to version 0.2.14.

Have you ever installed or tried to install pyhiveapi manually using any of the 2 commands below on the command line?

Sudo pip install pyhiveapi 

Pip3 install pyhiveapi 


If you have tried running any of the above you have 2 versions of pyhiveapi installed on your machine and it’s using the old one as the error is looking for the attributes class and it doesn’t exist in older versions than 0.2.14


Please run one of the following commands based on if you use pip or pip3 if you run either of them and get an error please rerun with sudo.

Pip uninstall pyhiveapi 
Or
Pip3 uninstall pyhiveapi 

Let me know if that fixes anything.

Thanks
Khole

**Comment by tmoore22** [comment]
I had previously installed pyhiveapi with pip3, but have upgraded hass-docker many time in the past.

And…

bash-4.4# pip3 uninstall pyhiveapi
Uninstalling pyhiveapi-0.2.14:
  /usr/bin/pyhiveapi
  /usr/lib/python3.6/site-packages/pyhiveapi-0.2.14.dist-info/DESCRIPTION.rst
  /usr/lib/python3.6/site-packages/pyhiveapi-0.2.14.dist-info/INSTALLER
  /usr/lib/python3.6/site-packages/pyhiveapi-0.2.14.dist-info/METADATA
  /usr/lib/python3.6/site-packages/pyhiveapi-0.2.14.dist-info/RECORD
  /usr/lib/python3.6/site-packages/pyhiveapi-0.2.14.dist-info/WHEEL
  /usr/lib/python3.6/site-packages/pyhiveapi-0.2.14.dist-info/entry_points.txt
  /usr/lib/python3.6/site-packages/pyhiveapi-0.2.14.dist-info/metadata.json
  /usr/lib/python3.6/site-packages/pyhiveapi-0.2.14.dist-info/top_level.txt
  /usr/lib/python3.6/site-packages/pyhiveapi/__init__.py
  /usr/lib/python3.6/site-packages/pyhiveapi/__pycache__/__init__.cpython-36.pyc
  /usr/lib/python3.6/site-packages/pyhiveapi/__pycache__/pyhiveapi.cpython-36.pyc
  /usr/lib/python3.6/site-packages/pyhiveapi/pyhiveapi.py
Proceed (y/n)? y
  Successfully uninstalled pyhiveapi-0.2.14

**Comment by tmoore22** [comment]
2018-04-30 18:07:52 INFO (MainThread) [homeassistant.setup] Setting up hive
2018-04-30 18:07:59 ERROR (MainThread) [homeassistant.setup] Error during setup of component hive
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 145, in _async_setup_component
    component.setup, hass, processed_config)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/hive.py", line 76, in setup
    session.attributes = Pyhiveapi.Attributes()
AttributeError: type object 'Pyhiveapi' has no attribute 'Attributes'
2018-04-30 18:07:59 INFO (MainThread) [homeassistant.core] Bus:Handling <Event system_log_event[L]: timestamp=1525108079.7721066, level=ERROR, message=Error during setup of component hive, exception=Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 145, in _async_setup_component
    component.setup, hass, processed_config)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/hive.py", line 76, in setup
    session.attributes = Pyhiveapi.Attributes()
AttributeError: type object 'Pyhiveapi' has no attribute 'Attributes'
, source=components/hive.py>
2018-04-30 18:07:59 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=persistent_notification, service=create, service_data=title=Invalid config, message=The following components and platforms could not be set up:

- [hive](https://home-assistant.io/components/hive/)

Please check your config., notification_id=invalid_config, service_call_id=3040899824-4>
2018-04-30 18:08:00 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=persistent_notification.invalid_config, old_state=None, new_state=<state persistent_notification.invalid_config=notifying; title=Invalid config, message=The following components and platforms could not be set up:

- [hive](https://home-assistant.io/components/hive/)

Please check your config. @ 2018-04-30T18:08:00.052607+01:00>>

From: Tim Moore <tmoore@live.co.uk>
Sent: 30 April 2018 18:53
To: Rendili/pyhiveapi <reply@reply.github.com>; Rendili/pyhiveapi <pyhiveapi@noreply.github.com>
Cc: tmoore22 <mail@tmoore.co.uk>; Mention <mention@noreply.github.com>
Subject: RE: [Rendili/pyhiveapi] New issue with binary_sensors not updating (#3)

I had previously installed pyhiveapi with pip3, but have upgraded hass-docker many time in the past.

And…

bash-4.4# pip3 uninstall pyhiveapi
Uninstalling pyhiveapi-0.2.14:
  /usr/bin/pyhiveapi
  /usr/lib/python3.6/site-packages/pyhiveapi-0.2.14.dist-info/DESCRIPTION.rst
  /usr/lib/python3.6/site-packages/pyhiveapi-0.2.14.dist-info/INSTALLER
  /usr/lib/python3.6/site-packages/pyhiveapi-0.2.14.dist-info/METADATA
  /usr/lib/python3.6/site-packages/pyhiveapi-0.2.14.dist-info/RECORD
  /usr/lib/python3.6/site-packages/pyhiveapi-0.2.14.dist-info/WHEEL
  /usr/lib/python3.6/site-packages/pyhiveapi-0.2.14.dist-info/entry_points.txt
  /usr/lib/python3.6/site-packages/pyhiveapi-0.2.14.dist-info/metadata.json
  /usr/lib/python3.6/site-packages/pyhiveapi-0.2.14.dist-info/top_level.txt
  /usr/lib/python3.6/site-packages/pyhiveapi/__init__.py
  /usr/lib/python3.6/site-packages/pyhiveapi/__pycache__/__init__.cpython-36.pyc
  /usr/lib/python3.6/site-packages/pyhiveapi/__pycache__/pyhiveapi.cpython-36.pyc
  /usr/lib/python3.6/site-packages/pyhiveapi/pyhiveapi.py
Proceed (y/n)? y
  Successfully uninstalled pyhiveapi-0.2.14

**Comment by tmoore22** [comment]
bash-4.4# pip3 show pyhiveapi
Name: pyhiveapi
Version: 0.2.14
Summary: A Python library to interface with the Hive API
Home-page: https://github.com/Rendili/pyhiveapi
Author: Rendili
Author-email: rendili@outlook.com
License: MIT
Location: /usr/lib/python3.6/site-packages
Requires:

**Comment by tmoore22** [comment]
It looks like the pyhiveapi.py is not the correct encoding…

""" Pyhiveapi"""^M
import operator^M
from datetime import datetime^M
from datetime import timedelta^M
import threading^M
import time^M
import requests^M
import colorsys^M
import os^M
^M
HIVE_NODE_UPDATE_INTERVAL_DEFAULT = 120^M
HIVE_WEATHER_UPDATE_INTERVAL_DEFAULT = 600^M
MINUTES_BETWEEN_LOGONS = 15^M
^M
NODE_ATTRIBS = {"Header": "HeaderText"}^M
^M
^M
class HiveDevices:^M
    """Initiate Hive Devices Class."""^M
^M
    hub = []^M
    thermostat = []^M
    boiler_module = []^M
    plug = []^M
    light = []^M
    sensors = []^M
    id_list = {}^M
^M
^M
class HiveProducts:^M
    """Initiate Hive Products Class."""^M
^M
    heating = []^M
    hotwater = []^M
    light = []^M
    plug = []^M
    sensors = []^M
    id_list = {}^M
^M

**Comment by tmoore22** [comment]
Ok, solved it.

I had also 0.2.11 version installed to: /config/deps/lib/python3.6/site-packages – now removed

Now, I am using pyhiveapi 0.2.14 😊

Initial results look good, will feedback with more news soon!

Thanks!

From: Tim Moore <tmoore@live.co.uk>
Sent: 30 April 2018 20:11
To: Tim Moore <tmoore@live.co.uk>; Rendili/pyhiveapi <reply@reply.github.com>; Rendili/pyhiveapi <pyhiveapi@noreply.github.com>
Cc: tmoore22 <mail@tmoore.co.uk>; Mention <mention@noreply.github.com>
Subject: RE: [Rendili/pyhiveapi] New issue with binary_sensors not updating (#3)

It looks like the pyhiveapi.py is not the correct encoding…

""" Pyhiveapi"""^M
import operator^M
from datetime import datetime^M
from datetime import timedelta^M
import threading^M
import time^M
import requests^M
import colorsys^M
import os^M
^M
HIVE_NODE_UPDATE_INTERVAL_DEFAULT = 120^M
HIVE_WEATHER_UPDATE_INTERVAL_DEFAULT = 600^M
MINUTES_BETWEEN_LOGONS = 15^M
^M
NODE_ATTRIBS = {"Header": "HeaderText"}^M
^M
^M
class HiveDevices:^M
    """Initiate Hive Devices Class."""^M
^M
    hub = []^M
    thermostat = []^M
    boiler_module = []^M
    plug = []^M
    light = []^M
    sensors = []^M
    id_list = {}^M
^M
^M
class HiveProducts:^M
    """Initiate Hive Products Class."""^M
^M
    heating = []^M
    hotwater = []^M
    light = []^M
    plug = []^M
    sensors = []^M
    id_list = {}^M
^M

**Comment by KJonline** [comment]
Hi @tmoore22 

Everything ok with your motion sensors now?

**Comment by tmoore22** [comment]
Yes, Great 😊 motion sensors are working now! Sorry for the late reply, have been away travelling..

**Comment by KJonline** [comment]
Thanks @tmoore22 I’ll close the issue now
